### ISSUE TITLE
Why javaScriptStyle then python_style?

### ISSUE THREAD

**Issue by mikemaccana** [JerrySievert/mongolike#12]
This looks awesome! Quick question: I notice some methods (getIndexes) are camel case per JavaScript itself, others (create_collection) use underscores - is there a particular rule here?

**Comment by JerrySievert** [comment]
coding at different times, not checking my own conventions when continuing.  the project has been going for a couple of years, and i switch in and out of languages and conventions way too much - it's a curse of working on too many open source projects :)

**Comment by JerrySievert** [comment]
but, i will look at cleaning up as a future release - i'm hoping an upcoming speaking engagement will spark more interest in this project.
